"""initial_schema

Revision ID: 3f82f965fb25
Revises: 
Create Date: 2026-06-20 11:54:39.393141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f82f965fb25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('api_endpoint', sa.String(length=256), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('inspection_prompt_template', sa.Text(), nullable=True),
    sa.Column('fault_prompt_template', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    # head_id -> users.id 的外键延后到 users 表创建后补建，避免 departments ↔ users 循环依赖导致 CREATE 失败
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_firmwares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('firmware_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(length=512), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('md5_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('min_compatible_hardware', sa.String(length=256), nullable=True),
    sa.Column('upgrade_guide', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_firmwares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_firmwares_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_firmwares_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_firmwares_model'), ['model'], unique=False)

    op.create_table('device_sub_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fault_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inspection_device_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_category', sa.String(length=32), nullable=True),
    sa.Column('device_sub_type', sa.String(length=64), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('inspection_type', sa.String(length=32), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=True),
    sa.Column('customer_tier', sa.String(length=8), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('device_sub_type', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('template_category', sa.String(length=32), nullable=True),
    sa.Column('report_section_key', sa.String(length=8), nullable=True),
    sa.Column('report_section_name', sa.String(length=64), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_is_active', ['is_active'], unique=False)

    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('specification', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('realname', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # 补建延后的 departments.head_id -> users.id 外键（users 现已存在）。
    # 用 batch_alter_table 以兼容 SQLite（SQLite 不支持直接 ALTER 加约束，需 copy-and-move）
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_departments_head_id_users', 'users', ['head_id'], ['id'])
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('has_onsite', sa.Boolean(), nullable=True),
    sa.Column('has_drill', sa.Boolean(), nullable=True),
    sa.Column('inspection_frequency', sa.String(length=16), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['customer_categories.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('form_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=32), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('form_data_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_drafts_user_id'), ['user_id'], unique=False)

    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspectors_user_id'), ['user_id'], unique=True)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('spare_part_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_code', name='uq_role_perm')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_code'), ['permission_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('spare_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_stocks_spare_part_id'), ['spare_part_id'], unique=False)

    op.create_table('task_device_template_link',
    sa.Column('task_template_id', sa.Integer(), nullable=False),
    sa.Column('device_template_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_template_id'], ['inspection_device_templates.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['inspection_task_templates.id'], ),
    sa.PrimaryKeyConstraint('task_template_id', 'device_template_id')
    )
    op.create_table('user_dashboard_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cards_json', sa.Text(), nullable=True),
    sa.Column('sidebar_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dashboard_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.Column('grant_type', sa.String(length=8), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_code', name='uq_user_perm')
    )
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index('ix_up_expire', ['expire_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('network_type', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('login_method', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('interface', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('rule_version', sa.String(length=128), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('cert_expiry_date', sa.Date(), nullable=True),
    sa.Column('is_maintenance', sa.Boolean(), nullable=True),
    sa.Column('is_in_use', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_is_in_use'), ['is_in_use'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_license_expiry'), ['license_expiry'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rack_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rack_locations_customer_id'), ['customer_id'], unique=False)

    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('spare_part_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('sales_date', sa.Date(), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('upload_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('inspection_frequency', sa.String(length=32), nullable=True),
    sa.Column('inspection_template_id', sa.Integer(), nullable=True),
    sa.Column('last_generated_date', sa.Date(), nullable=True),
    sa.Column('auto_generate_tasks', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inspection_template_id'], ['inspection_templates.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_collect_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('commands_json', sa.Text(), nullable=True),
    sa.Column('snmp_oids_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_collect_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_collect_tasks_device_id'), ['device_id'], unique=False)

    op.create_table('device_config_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=32), nullable=True),
    sa.Column('config_content', sa.Text(), nullable=True),
    sa.Column('backup_method', sa.String(length=32), nullable=True),
    sa.Column('backup_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_config_backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_config_backups_device_id'), ['device_id'], unique=False)

    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('login_method', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('password_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credentials_device_id'), ['device_id'], unique=False)

    op.create_table('device_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('peer_ip', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_interfaces_device_id'), ['device_id'], unique=False)

    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_history_device_id'), ['device_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('total_u', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('pdu_total_w', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['rack_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racks_location_id'), ['location_id'], unique=False)

    op.create_table('inspection_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('inspector_ids', sa.String(length=256), nullable=True),
    sa.Column('device_ids_json', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('template_category', sa.String(length=32), nullable=True),
    sa.Column('completion_data_json', sa.Text(), nullable=True),
    sa.Column('template_ids_json', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['inspection_task_templates.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('manager', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack_installs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('manual_name', sa.String(length=128), nullable=True),
    sa.Column('manual_brand', sa.String(length=64), nullable=True),
    sa.Column('manual_model', sa.String(length=64), nullable=True),
    sa.Column('manual_ip', sa.String(length=64), nullable=True),
    sa.Column('start_u', sa.Integer(), nullable=True),
    sa.Column('occupy_u', sa.Integer(), nullable=True),
    sa.Column('rated_w', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rack_installs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rack_installs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rack_installs_rack_id'), ['rack_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('inspector', sa.String(length=64), nullable=True),
    sa.Column('inspector_user_id', sa.Integer(), nullable=True),
    sa.Column('inspector_name', sa.String(length=64), nullable=True),
    sa.Column('inspector_phone', sa.String(length=32), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('overall_status', sa.String(length=32), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('sections_json', sa.Text(), nullable=True),
    sa.Column('abnormal_items_json', sa.Text(), nullable=True),
    sa.Column('report_file', sa.String(length=256), nullable=True),
    sa.Column('field_values_json', sa.Text(), nullable=True),
    sa.Column('skip_reasons_json', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_inspection_date'), ['inspection_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspector_user_id'), ['inspector_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_overall_status'), ['overall_status'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reporter', sa.String(length=64), nullable=True),
    sa.Column('reporter_phone', sa.String(length=32), nullable=True),
    sa.Column('related_inspection_id', sa.Integer(), nullable=True),
    sa.Column('related_device_id', sa.Integer(), nullable=True),
    sa.Column('fault_category_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.Column('assigned_by', sa.String(length=64), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('audit_status', sa.String(length=16), nullable=True),
    sa.Column('audit_by', sa.String(length=64), nullable=True),
    sa.Column('audit_at', sa.DateTime(), nullable=True),
    sa.Column('audit_comment', sa.Text(), nullable=True),
    sa.Column('accept_status', sa.String(length=16), nullable=True),
    sa.Column('accept_by', sa.String(length=64), nullable=True),
    sa.Column('accept_at', sa.DateTime(), nullable=True),
    sa.Column('accept_comment', sa.Text(), nullable=True),
    sa.Column('service_duration', sa.Integer(), nullable=True),
    sa.Column('report_file', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fault_category_level1', sa.String(length=64), nullable=True),
    sa.Column('fault_category_level2', sa.String(length=64), nullable=True),
    sa.Column('symptoms_json', sa.Text(), nullable=True),
    sa.Column('affected_components_json', sa.Text(), nullable=True),
    sa.Column('resolution_steps_json', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=64), nullable=True),
    sa.Column('severity_level', sa.String(length=16), nullable=True),
    sa.Column('impact_scope', sa.String(length=128), nullable=True),
    sa.Column('normalized_tags', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fault_category_id'], ['fault_types.id'], ),
    sa.ForeignKeyConstraint(['related_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['related_inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)

    op.create_table('faults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('handler', sa.String(length=64), nullable=True),
    sa.Column('fault_time', sa.DateTime(), nullable=True),
    sa.Column('fault_type', sa.String(length=64), nullable=True),
    sa.Column('fault_description', sa.Text(), nullable=True),
    sa.Column('impact_range', sa.String(length=256), nullable=True),
    sa.Column('fault_cause', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('recovery_time', sa.DateTime(), nullable=True),
    sa.Column('report_file', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fault_category_level1', sa.String(length=64), nullable=True),
    sa.Column('fault_category_level2', sa.String(length=64), nullable=True),
    sa.Column('symptoms_json', sa.Text(), nullable=True),
    sa.Column('affected_components_json', sa.Text(), nullable=True),
    sa.Column('resolution_steps_json', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=64), nullable=True),
    sa.Column('severity_level', sa.String(length=16), nullable=True),
    sa.Column('impact_scope', sa.String(length=128), nullable=True),
    sa.Column('normalized_tags', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faults_fault_time'), ['fault_time'], unique=False)

    op.create_table('ticket_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_logs_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('related_fault_id', sa.Integer(), nullable=True),
    sa.Column('related_device_type', sa.String(length=64), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_fault_id'], ['faults.id'], ),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_ext', sa.String(length=16), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_attachments_knowledge_id'), ['knowledge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_attachments_knowledge_id'))

    op.drop_table('knowledge_attachments')
    op.drop_table('knowledge_base')
    with op.batch_alter_table('ticket_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_logs_ticket_id'))

    op.drop_table('ticket_logs')
    with op.batch_alter_table('faults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faults_fault_time'))

    op.drop_table('faults')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_tickets_number'))

    op.drop_table('tickets')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_overall_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspector_user_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspection_date'))

    op.drop_table('inspections')
    with op.batch_alter_table('rack_installs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rack_installs_rack_id'))
        batch_op.drop_index(batch_op.f('ix_rack_installs_device_id'))

    op.drop_table('rack_installs')
    op.drop_table('projects')
    op.drop_table('inspection_tasks')
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racks_location_id'))

    op.drop_table('racks')
    op.drop_table('quotations')
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_history_device_id'))

    op.drop_table('password_history')
    with op.batch_alter_table('device_interfaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_interfaces_device_id'))

    op.drop_table('device_interfaces')
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_credentials_device_id'))

    op.drop_table('device_credentials')
    with op.batch_alter_table('device_config_backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_config_backups_device_id'))

    op.drop_table('device_config_backups')
    with op.batch_alter_table('device_collect_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_collect_tasks_device_id'))

    op.drop_table('device_collect_tasks')
    op.drop_table('contracts')
    op.drop_table('topologies')
    op.drop_table('sales_orders')
    with op.batch_alter_table('rack_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rack_locations_customer_id'))

    op.drop_table('rack_locations')
    op.drop_table('opportunities')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_license_expiry'))
        batch_op.drop_index(batch_op.f('ix_devices_is_in_use'))
        batch_op.drop_index(batch_op.f('ix_devices_ip_address'))

    op.drop_table('devices')
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permissions_user_id'))
        batch_op.drop_index('ix_up_expire')

    op.drop_table('user_permissions')
    with op.batch_alter_table('user_dashboard_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_preferences_user_id'))

    op.drop_table('user_dashboard_preferences')
    op.drop_table('task_device_template_link')
    with op.batch_alter_table('spare_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_stocks_spare_part_id'))

    op.drop_table('spare_stocks')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_code'))

    op.drop_table('role_permissions')
    op.drop_table('purchase_orders')
    with op.batch_alter_table('inspectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspectors_user_id'))

    op.drop_table('inspectors')
    with op.batch_alter_table('form_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_drafts_user_id'))

    op.drop_table('form_drafts')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_level'))

    op.drop_table('customers')
    # 先删延后补建的 departments.head_id 外键，再删 users（否则 PG/SQLite 会因被引用而拒绝 drop）。
    # batch 模式兼容 SQLite
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_head_id_users', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('spare_parts')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_is_active')

    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('permissions')
    op.drop_table('network_types')
    op.drop_table('inspection_templates')
    op.drop_table('inspection_task_templates')
    op.drop_table('inspection_device_templates')
    op.drop_table('fault_types')
    op.drop_table('device_types')
    op.drop_table('device_sub_types')
    with op.batch_alter_table('device_firmwares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_firmwares_model'))
        batch_op.drop_index(batch_op.f('ix_device_firmwares_is_latest'))
        batch_op.drop_index(batch_op.f('ix_device_firmwares_brand'))

    op.drop_table('device_firmwares')
    op.drop_table('departments')
    op.drop_table('customer_categories')
    op.drop_table('custom_fields')
    op.drop_table('brands')
    op.drop_table('ai_config')
    # ### end Alembic commands ###
