#!/usr/bin/env python3
"""从后端状态常量生成前端只读 TypeScript；支持 CI 漂移检查。"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from utils.constants import STATUS_CATALOG  # noqa: E402


TARGET = ROOT / 'frontend' / 'src' / 'utils' / 'status.generated.ts'


def _json(value) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def render() -> str:
    lines = [
        '/**',
        ' * AUTO-GENERATED by scripts/generate_frontend_status.py.',
        ' * Source of truth: utils/constants.py. Do not edit this file directly.',
        ' */',
        '',
        "export type TagType = 'primary' | 'success' | 'warning' | 'danger' | 'info'",
        '',
    ]
    for export_name, definition in STATUS_CATALOG.items():
        lines.extend([
            f'export const {export_name} = {_json(definition["values"])} as const',
            '',
            f'export const {export_name}_TAG: Record<string, TagType> = '
            f'{_json(definition["tags"])}',
            '',
        ])
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='仅检查生成物是否与后端真源一致')
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = TARGET.read_text(encoding='utf-8') if TARGET.exists() else ''
        if actual != expected:
            print(f'{TARGET.relative_to(ROOT)} is stale; run {Path(__file__).name}')
            return 1
        return 0
    TARGET.write_text(expected, encoding='utf-8', newline='\n')
    print(f'generated {TARGET.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
